version: '3.8'

services:
  backend:
    image: ghcr.io/${{ github.repository_owner }}/wiesenwahn-backend:latest
    restart: always
    volumes:
      - ./data:/app/db
      - ./logs:/app/logs
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - PASSWORD=${USER_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASS=${GMAIL_PASS}
    # Not exposed to outside world, only to frontend and within Docker network

  frontend:
    image: ghcr.io/${{ github.repository_owner }}/wiesenwahn-frontend:latest
    restart: always
    ports:
      - "8080:80"  # Exposed only on localhost for Nginx to proxy
    depends_on:
      - backend