version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file: ./server/.env
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    restart: always
    depends_on:
      - frontend

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "80:80"
    restart: always
