import base64
import os
import smtplib

from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build

from typing import Dict

from dotenv import load_dotenv

from .views import Booking, FormContent


# Function to find the human-readable details based on booking, now including workshift information and formatting in German
def get_booking_details(booking: Booking, form_content: Dict) -> str:
    # Retrieve ticket option
    ticket_option = next((to for to in form_content["ticket_options"] if to["id"] == booking.ticket_id), None)
    ticket_info = f"Ticket: {ticket_option['title']} - Preis: {ticket_option['price']}€" if ticket_option else "Ticket: Nicht gefunden"

    # Retrieve beverage option
    beverage_option = next((bo for bo in form_content['beverage_options'] if bo['id'] == booking.beverage_id), None)
    beverage_info = f"Getränkeoption: {beverage_option['title']} - Preis: {beverage_option['price']}€" if beverage_option else "Getränkeoption: Nicht gefunden"

    # Function to find and format timeslot information
    def format_timeslot_info(timeslot_id):
        for ws in form_content['work_shifts']:
            for ts in ws['time_slots']:
                if ts['id'] == timeslot_id:
                    return f"{ws['title']}, Zeitfenster: {ts['title']}, Von: {ts['start_time']}, Bis: {ts['end_time']}"
        return "Zeitfenster: Nicht gefunden"

    # Time slots and work shifts
    timeslot_info = "Du hast folgende Prioritäten für deine Supporterschicht gewählt:\n"
    timeslot_info += "\n".join([
        f"Priorität {i + 1}: {format_timeslot_info(ts_id)}"
        for i, ts_id in
        enumerate([booking.timeslot_priority_1, booking.timeslot_priority_2, booking.timeslot_priority_3])
    ])
    timeslot_info += f"\nDu hast dicht bereit erklärt maximal {booking.amount_shifts} Schichten zu übernehmen."

    # Materials
    materials_info = "Du bringst mit:\n" + "\n".join(
        [f"- {material['title']}" for material in form_content['materials'] if
         material['id'] in booking.material_ids])
    materials_info = materials_info if booking.material_ids else "Du bringst keine Materialien mit."

    # Combine all information
    details = f"{ticket_info}\n\n{beverage_info}\n\n{timeslot_info}\n\n{materials_info}\n\nGesamtpreis: {booking.total_price}€"
    return details


# Adjusting the send_confirmation_mail function slightly to include the new get_booking_details implementation
def send_confirmation_mail(booking: Booking, form_content: Dict) -> None:
    load_dotenv()
    gmail_user = os.environ.get("GMAIL_USER")
    gmail_password = os.environ.get("GMAIL_PASS")

    # Booking details in German, as generated by your get_booking_details function
    booking_details_html = get_booking_details(booking, form_content).replace('\n', '<br>')

    # Prepare the HTML message
    html = f"""
    <html>
    <head>
    <style>
  body {{
    font-family: 'Trebuchet MS', Arial, sans-serif; /* A more casual, friendly font */
    margin: 20px;
    color: #333;
    background-color: #ffffff; /* Soft green background */
  }}
  .header {{
    background-color: #76b947; /* Vibrant green for the header */
    color: #ffffff;
    padding: 20px;
    text-align: center;
    border-radius: 10px;
  }}
  .content {{
    margin-top: 20px;
    background-color: #d1ffd1; /* Keep content background light for readability */
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1); /* Soft shadow for depth */
  }}
  .footer {{
    margin-top: 20px;
    font-size: small;
    text-align: center;
    padding: 20px;
  }}
  a {{
    color: #428bca; /* Ensure links are noticeable */
  }}
</style>
    </head>
    <body>
    <div class="header">
      <h1>Willkommen zum Weiher Wald & Wiesenwahn!</h1>
      <p>29.08. - 01.09.2024</p>
    </div>
    <div class="content">
      Liebe/r <strong>{booking.first_name} {booking.last_name}</strong>,<br><br>
      Wir freuen uns, dass du bei unserem 5 jährigen Jubiläum dabei bist! Hier sind die Details deiner Buchung:<br><br>
      {booking_details_html}<br><br>
      Alle weiteren Informationen teilen wir dir rechtzeitig in der Whatsapp Gruppe mit.<br><br>
      Bis bald in Poppenwind!<br><br>
      &#127881; Dein Wiesenwahn Team &#127882;
    </div>
    </body>
    </html>
    """

    msg = MIMEMultipart('alternative')
    msg['From'] = gmail_user
    msg['To'] = booking.email
    msg['Subject'] = '5 Jahre Wiesenwahn - Du bist dabei!'

    # Attach the HTML message
    msg.attach(MIMEText(html, 'html'))

    # save the email to a file
    with open("email.html", "w") as file:
        file.write(html)

    try:
        server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
        server.ehlo()
        server.login(gmail_user, gmail_password)
        server.sendmail(gmail_user, booking.email, msg.as_string())
        server.close()
        print("Email erfolgreich gesendet!")
    except Exception as e:
        print(f"Fehler beim Senden der E-Mail: {e}")

# Note: Replace 'your_email@gmail.com' and 'your_app_password' with your actual details.
